from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "data" / "maintenance-overrides.js"
VALID_COORDINATE_LEVELS = {"景区", "区县", "城市"}
VALID_CATEGORIES = {"nature", "water", "heritage", "settlement", "museum", "religious", "red", "leisure", "other"}
VALID_THEMES = {"nature", "culture", "family", "ancient", "red", "water"}
VALID_SEASONS = {"spring", "summer", "autumn", "winter"}


def load_payload(path: Path) -> dict[str, dict[str, Any]]:
    raw = json.loads(path.read_text(encoding="utf-8-sig"))
    rows = raw.get("overrides") or raw.get("maintenanceOverrides") or raw if isinstance(raw, dict) else raw

    if isinstance(rows, dict):
        iterable = [{**({"id": key} if "id" not in value else {}), **value} for key, value in rows.items() if isinstance(value, dict)]
    else:
        iterable = rows or []

    normalized: dict[str, dict[str, Any]] = {}
    for row in iterable:
        clean = normalize_row(row)
        if clean:
            normalized[clean["id"]] = clean
    return dict(sorted(normalized.items()))


def normalize_row(row: Any) -> dict[str, Any] | None:
    if not isinstance(row, dict):
        return None
    item_id = str(row.get("id") or "").strip()
    if not item_id:
        return None

    clean: dict[str, Any] = {
        "id": item_id,
        "name": string_field(row.get("name")),
        "displayName": string_field(row.get("displayName")),
        "province": string_field(row.get("province")),
        "city": string_field(row.get("city")),
        "updatedAt": string_field(row.get("updatedAt")) or datetime.now(timezone.utc).isoformat(),
    }

    lat, lng = number_field(row.get("lat")), number_field(row.get("lng"))
    if lat is not None and lng is not None and -90 <= lat <= 90 and -180 <= lng <= 180:
        clean["lat"] = round(lat, 6)
        clean["lng"] = round(lng, 6)

    coordinate_level = string_field(row.get("coordinateLevel"))
    if coordinate_level in VALID_COORDINATE_LEVELS:
        clean["coordinateLevel"] = coordinate_level

    coordinate_label = string_field(row.get("coordinateLabel"))
    if coordinate_label:
        clean["coordinateLabel"] = coordinate_label

    category = string_field(row.get("categoryOverride") or row.get("category"))
    if category in VALID_CATEGORIES:
        clean["categoryOverride"] = category

    themes = normalize_choices(row.get("themeOverride") or row.get("themes"), VALID_THEMES)
    if themes:
        clean["themeOverride"] = themes

    seasons = normalize_choices(row.get("seasonOverride") or row.get("seasons"), VALID_SEASONS)
    if seasons:
        clean["seasonOverride"] = seasons

    source_key = string_field(row.get("sourceKey"))
    if source_key:
        clean["sourceKey"] = source_key

    data_updated = string_field(row.get("dataUpdated"))
    if data_updated:
        clean["dataUpdated"] = data_updated

    note = string_field(row.get("note") or row.get("maintenanceNote"))
    if note:
        clean["note"] = note

    override_keys = {
        "lat",
        "lng",
        "coordinateLevel",
        "coordinateLabel",
        "categoryOverride",
        "themeOverride",
        "seasonOverride",
        "sourceKey",
        "dataUpdated",
        "note",
    }
    return clean if override_keys.intersection(clean) else None


def string_field(value: Any) -> str:
    return str(value or "").strip()


def number_field(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if number == number else None


def normalize_choices(value: Any, allowed: set[str]) -> list[str]:
    if isinstance(value, list):
        rows = value
    else:
        rows = str(value or "").replace("，", ",").split(",")
    clean: list[str] = []
    for row in rows:
        key = str(row or "").strip()
        if key in allowed and key not in clean:
            clean.append(key)
    return clean


def write_js(overrides: dict[str, dict[str, Any]], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    generated_at = datetime.now(timezone.utc).isoformat()
    content = (
        "// Generated by scripts/apply-maintenance-overrides.py. Do not edit by hand.\n"
        f"window.CHINA_MAINTENANCE_OVERRIDES = {json.dumps(overrides, ensure_ascii=False, indent=2)};\n"
        f"window.CHINA_MAINTENANCE_META = {json.dumps({'generatedAt': generated_at, 'count': len(overrides)}, ensure_ascii=False, indent=2)};\n"
    )
    out_path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Import exported maintenance overrides into the static data layer.")
    parser.add_argument("input", type=Path, help="JSON exported from the maintenance panel")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help=f"Output JS file, default: {DEFAULT_OUT}")
    parser.add_argument("--dry-run", action="store_true", help="Validate and summarize without writing")
    args = parser.parse_args()

    overrides = load_payload(args.input)
    corrected_coordinates = sum(1 for row in overrides.values() if "lat" in row and "lng" in row)

    if not args.dry_run:
        write_js(overrides, args.out)

    target = args.out if not args.dry_run else "(dry run)"
    print(f"maintenance overrides: {len(overrides)} -> {target}")
    print(f"coordinate overrides: {corrected_coordinates}")


if __name__ == "__main__":
    main()
