from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "data" / "image-review-decisions.js"
VALID_ACTIONS = {"keep", "replace", "delete", "missing"}


def load_payload(path: Path) -> dict[str, dict]:
    raw = json.loads(path.read_text(encoding="utf-8-sig"))
    decisions = raw.get("decisions") or raw.get("reviewDecisions") or raw if isinstance(raw, dict) else raw
    if isinstance(decisions, dict):
        rows = decisions.values()
    else:
        rows = decisions

    normalized: dict[str, dict] = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        item_id = str(row.get("id") or "").strip()
        action = str(row.get("action") or "").strip()
        if not item_id or action not in VALID_ACTIONS:
            continue
        clean = {
            "id": item_id,
            "name": row.get("name") or row.get("displayName") or "",
            "displayName": row.get("displayName") or row.get("name") or "",
            "province": row.get("province") or "",
            "city": row.get("city") or "",
            "action": action,
            "note": row.get("note") or "",
            "imageUrl": row.get("imageUrl") or "",
            "pageUrl": row.get("pageUrl") or "",
            "updatedAt": row.get("updatedAt") or datetime.now(timezone.utc).isoformat(),
        }
        replacement = replacement_url_from_note(str(row.get("replacementUrl") or "")) or replacement_url_from_note(clean["note"])
        if replacement:
            clean["replacementUrl"] = replacement
        normalized[item_id] = clean
    return dict(sorted(normalized.items()))


def replacement_url_from_note(note: str) -> str:
    value = note.strip().replace("\\", "/")
    if value.startswith("assets/images/") and value.lower().endswith((".jpg", ".jpeg", ".png", ".webp")):
        return value
    return ""


def write_js(decisions: dict[str, dict], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    generated_at = datetime.now(timezone.utc).isoformat()
    content = (
        "// Generated by scripts/apply-image-review.py. Do not edit by hand.\n"
        f"window.CHINA_IMAGE_REVIEW_DECISIONS = {json.dumps(decisions, ensure_ascii=False, indent=2)};\n"
        f"window.CHINA_IMAGE_REVIEW_META = {json.dumps({'generatedAt': generated_at, 'count': len(decisions)}, ensure_ascii=False, indent=2)};\n"
    )
    out_path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Import exported image review decisions into the static data layer.")
    parser.add_argument("input", type=Path, help="JSON exported from the image review panel")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help=f"Output JS file, default: {DEFAULT_OUT}")
    parser.add_argument("--dry-run", action="store_true", help="Validate and summarize without writing")
    args = parser.parse_args()

    decisions = load_payload(args.input)
    counts = {action: 0 for action in sorted(VALID_ACTIONS)}
    for row in decisions.values():
        counts[row["action"]] += 1

    if not args.dry_run:
        write_js(decisions, args.out)

    target = args.out if not args.dry_run else "(dry run)"
    print(f"review decisions: {len(decisions)} -> {target}")
    print("actions:", ", ".join(f"{key}={value}" for key, value in counts.items()))


if __name__ == "__main__":
    main()
